spring:

  application:
    name: sabangnet-server

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa


  jpa:
    open-in-view: true
    hibernate:
      jdbc:
        batch_size: 20
      order_inserts: true
      order_updates: true
      generate_statistics: true
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8099