spring:
  ai:
    openai:
      api-key: sk-proj-Nj46b6tsLT7t0m60z2XzT3BlbkFJEE9fDv1rrro2QtjbuGGJ

    vertex:
      ai:
        gemini:
          project-id: sabangnet-431103
          location: asia-northeast3

  application:
    name: sabangnet-server

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa


  jpa:
    open-in-view: true
    hibernate:
      jdbc:
      order_inserts: true
      order_updates: true
      generate_statistics: true
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8099